version: "3.8"

services:
  frontend:
    container_name: dl-frontend
    image: node:22.13-alpine3.20
    entrypoint: /bin/sh
    ports:
      - "3000:3000"
    working_dir: /srv/app
    volumes:
      - ./frontend:/srv/app
    tty: true
  backend:
    container_name: dl-backend
    image: nginx:1.26-alpine
    ports:
      - "5000:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: dl-php
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    container_name: dl-db
    image: mysql:8.0.38
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: dl-es
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.security.authc.api_key.enabled: "true"
      node.name: "es01"
      network.host: "0.0.0.0"
      cluster.name: "es-docker-cluster"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
    driver: local