framework:
    messenger:
        default_bus: command.sync.bus
        buses:
            command.sync.bus:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
            event.sync.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            sync:
                dsn: 'sync://'
            failed: 'doctrine://default?queue_name=failed'
        failure_transport: failed
        routing:
            App\Shared\Application\Command\Sync\Command: sync