# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_dir: '%env(UPLOAD_DIR)%'
    elastic_host: '%env(ELASTIC_HOST)%'
    elastic_port: '%env(ELASTIC_PORT)%'
    elastic_user: '%env(ELASTIC_USER)%'
    elastic_password: '%env(ELASTIC_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Document/Domain/Entity/'
            - '../src/Document/Domain/Enum/'
            - '../src/Document/Application/View/'

    _instanceof:
        App\Shared\Application\Command\Sync\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: command.sync.bus }
        App\Shared\Application\Event\Sync\EventHandler:
            tags:
                - { name: 'messenger.message_handler', bus: event.sync.bus }
        App\Document\Application\Service\FileReader:
            tags:
                - { name: 'app.file_reader' }

    App\Document\Application\Service\FileReaderProvider:
        arguments:
            $readers: !tagged_iterator app.file_reader

    App\Document\Infrastructure\Service\FileService:
        arguments:
            $uploadDir: '%upload_dir%'

    App\Document\Infrastructure\Service\PdfReader:
        arguments:
            $parser: '@Smalot\PdfParser\Parser'

    Smalot\PdfParser\Parser: ~

    App\Shared\Infrastructure\Elasticsearch\ElasticsearchClient:
        arguments:
            $environment: '%kernel.environment%'
            $host: '%elastic_host%'
            $port: '%elastic_port%'
            $user: '%elastic_user%'
            $password: '%elastic_password%'

    App\User\Infrastructure\Service\UserPasswordHasher:
        arguments:
            $environment: '%kernel.environment%'

    App\User\Infrastructure\Security\Listener\JwtCreatedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_jwt_created' }

    App\Shared\Infrastructure\Listener\ExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
